In [1]:
class Animal:
    def eat(self):
        print("Animal is eating")


class Dog(Animal):
    pass


d = Dog()
d.eat()

Animal is eating

In [2]:
pip install pandas

Requirement already satisfied: pandas in d:\anaconda\lib\site-packages (2.2.3)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy>=1.26.0 in d:\anaconda\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\anaconda\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in d:\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in d:\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

In [6]:
#read a csv file
df=pd.read_csv("C:\\Users\\Ravishankar Kumar\\Desktop\\divorce-csv.csv")

In [7]:
df

,Atr1,Atr2,Atr3,Atr4,Atr5,Atr6,Atr7,Atr8,Atr9,Atr10,...,Atr46,Atr47,Atr48,Atr49,Atr50,Atr51,Atr52,Atr53,Atr54,Class
0,2,2,4,1,0,0,0,0,0,0,...,2,1,3,3,3,2,3,2,1,1
1,4,4,4,4,4,0,0,4,4,4,...,2,2,3,4,4,4,4,2,2,1
2,2,2,2,2,1,3,2,1,1,2,...,3,2,3,1,1,1,2,2,2,1
3,3,2,3,2,3,3,3,3,3,3,...,2,2,3,3,3,3,2,2,2,1
4,2,2,1,1,1,1,0,0,0,0,...,2,1,2,3,2,2,2,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,0,0,0,0,0,0,0,0,0,0,...,1,0,4,1,1,4,2,2,2,0
166,0,0,0,0,0,0,0,0,0,0,...,4,1,2,2,2,2,3,2,2,0
167,1,1,0,0,0,0,0,0,0,1,...,3,0,2,0,1,1,3,0,0,0
168,0,0,0,0,0,0,0,0,0,0,...,3,3,2,2,3,2,4,3,1,0
169,0,0,0,0,0,0,0,1,0,0,...,3,4,4,0,1,3,3,3,1,0

In [8]:
df.head()

,Atr1,Atr2,Atr3,Atr4,Atr5,Atr6,Atr7,Atr8,Atr9,Atr10,...,Atr46,Atr47,Atr48,Atr49,Atr50,Atr51,Atr52,Atr53,Atr54,Class
0,2,2,4,1,0,0,0,0,0,0,...,2,1,3,3,3,2,3,2,1,1
1,4,4,4,4,4,0,0,4,4,4,...,2,2,3,4,4,4,4,2,2,1
2,2,2,2,2,1,3,2,1,1,2,...,3,2,3,1,1,1,2,2,2,1
3,3,2,3,2,3,3,3,3,3,3,...,2,2,3,3,3,3,2,2,2,1
4,2,2,1,1,1,1,0,0,0,0,...,2,1,2,3,2,2,2,1,0,1

In [9]:
df.shape

(170, 55)

In [10]:
#data types
df.dtypes

Atr1     int64
Atr2     int64
Atr3     int64
Atr4     int64
Atr5     int64
Atr6     int64
Atr7     int64
Atr8     int64
Atr9     int64
Atr10    int64
Atr11    int64
Atr12    int64
Atr13    int64
Atr14    int64
Atr15    int64
Atr16    int64
Atr17    int64
Atr18    int64
Atr19    int64
Atr20    int64
Atr21    int64
Atr22    int64
Atr23    int64
Atr24    int64
Atr25    int64
Atr26    int64
Atr27    int64
Atr28    int64
Atr29    int64
Atr30    int64
Atr31    int64
Atr32    int64
Atr33    int64
Atr34    int64
Atr35    int64
Atr36    int64
Atr37    int64
Atr38    int64
Atr39    int64
Atr40    int64
Atr41    int64
Atr42    int64
Atr43    int64
Atr44    int64
Atr45    int64
Atr46    int64
Atr47    int64
Atr48    int64
Atr49    int64
Atr50    int64
Atr51    int64
Atr52    int64
Atr53    int64
Atr54    int64
Class    int64
dtype: object

In [11]:
#column names
df.columns

Index(['Atr1', 'Atr2', 'Atr3', 'Atr4', 'Atr5', 'Atr6', 'Atr7', 'Atr8', 'Atr9',
       'Atr10', 'Atr11', 'Atr12', 'Atr13', 'Atr14', 'Atr15', 'Atr16', 'Atr17',
       'Atr18', 'Atr19', 'Atr20', 'Atr21', 'Atr22', 'Atr23', 'Atr24', 'Atr25',
       'Atr26', 'Atr27', 'Atr28', 'Atr29', 'Atr30', 'Atr31', 'Atr32', 'Atr33',
       'Atr34', 'Atr35', 'Atr36', 'Atr37', 'Atr38', 'Atr39', 'Atr40', 'Atr41',
       'Atr42', 'Atr43', 'Atr44', 'Atr45', 'Atr46', 'Atr47', 'Atr48', 'Atr49',
       'Atr50', 'Atr51', 'Atr52', 'Atr53', 'Atr54', 'Class'],
      dtype='object')

In [13]:
#null values
df.count()

Atr1     170
Atr2     170
Atr3     170
Atr4     170
Atr5     170
Atr6     170
Atr7     170
Atr8     170
Atr9     170
Atr10    170
Atr11    170
Atr12    170
Atr13    170
Atr14    170
Atr15    170
Atr16    170
Atr17    170
Atr18    170
Atr19    170
Atr20    170
Atr21    170
Atr22    170
Atr23    170
Atr24    170
Atr25    170
Atr26    170
Atr27    170
Atr28    170
Atr29    170
Atr30    170
Atr31    170
Atr32    170
Atr33    170
Atr34    170
Atr35    170
Atr36    170
Atr37    170
Atr38    170
Atr39    170
Atr40    170
Atr41    170
Atr42    170
Atr43    170
Atr44    170
Atr45    170
Atr46    170
Atr47    170
Atr48    170
Atr49    170
Atr50    170
Atr51    170
Atr52    170
Atr53    170
Atr54    170
Class    170
dtype: int64

In [20]:
subset=df[['Atr1','Atr2','Atr3']]

In [21]:
print(subset)

     Atr1  Atr2  Atr3
0       2     2     4
1       4     4     4
2       2     2     2
3       3     2     3
4       2     2     1
..    ...   ...   ...
165     0     0     0
166     0     0     0
167     1     1     0
168     0     0     0
169     0     0     0

[170 rows x 3 columns]

In [22]:
subset.shape

(170, 3)

In [25]:
#sorting of data
sorted_df=df.sort_values(['Atr1','Atr2'],ascending=[True,False])
sorted_df

,Atr1,Atr2,Atr3,Atr4,Atr5,Atr6,Atr7,Atr8,Atr9,Atr10,...,Atr46,Atr47,Atr48,Atr49,Atr50,Atr51,Atr52,Atr53,Atr54,Class
96,0,3,1,0,0,0,0,0,0,0,...,1,1,4,0,0,2,0,0,0,0
150,0,3,2,0,0,0,0,0,0,0,...,4,4,3,1,1,1,2,0,1,0
113,0,2,2,1,0,0,0,0,0,2,...,0,0,3,1,1,1,0,3,0,0
121,0,2,2,1,0,0,0,0,0,2,...,0,0,3,1,1,1,0,3,0,0
140,0,2,0,0,0,1,0,0,0,0,...,1,2,2,1,0,1,3,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48,4,2,3,2,4,2,0,2,3,2,...,4,4,4,4,4,4,4,4,4,1
50,4,2,3,2,4,2,0,2,3,2,...,4,4,4,4,4,4,4,4,4,1
67,4,2,2,3,4,2,0,2,2,3,...,3,4,3,4,4,3,4,3,4,1
79,4,2,4,2,1,2,3,1,1,3,...,2,1,3,3,3,3,1,1,1,1
88,4,0,3,4,0,0,0,0,0,0,...,0,0,4,0,0,0,0,0,0,0

In [27]:
#grouping of data
grouped_df=df.groupby('Atr1')['Atr2'].mean()
grouped_df

Atr1
0    0.362319
1    0.777778
2    1.285714
3    2.914894
4    3.032258
Name: Atr2, dtype: float64

In [ ]:
#https://pandas.pydata.org/docs/user_guide/index.html#user-guide

In [28]:
import pandas as pd
pd.DataFrame({'A': [1, 2, 3]})

   A
0  1
1  2
2  3

In [31]:
import pandas as pd

pd.DataFrame({'A': [1, 2, 3]})

   A
0  1
1  2
2  3